### PR TITLE
Enable spec build system

### PR DESCRIPTION
**Pull request by VictorRodriguez**

### CODE REVIEW

**Comment by lsandov1** [comment]
thanks @VictorRodriguez. this is really cool. I have invited Luis Ponce  and Sergio Perez to this project. I want them to take a look on these and what they think first.

**Comment by VictorRodriguez** [comment]
Maybe I can present a basic demo

**Review by lsandov1 — COMMENTED** [review]
@VictorRodriguez in general terms, what is the difference between this pull request (10) and pull request 9?

**Comment by VictorRodriguez** [comment]
This one includes both: 

Support mock build
Enable SPEC build system using moc

PR  9 only mock build

**Pull request merged**
